name: Terraform Workflow

on:
  push:
    branches:
      - main
    paths:
    - "terraform/**"
  pull_request:
    branches:
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:


jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: 1.12.0
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
            
      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: terraform

      - name: Plan Terraform changes
        run: terraform plan
        working-directory: terraform

      - name: Apply Terraform changes
        run: terraform apply -auto-approve
        working-directory: terraform